resources:
- name: boshlite-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
- name: cf-release
  type: git
  source:
    branch: master
    ignore_paths:
    - dev_releases
    - git_hooks
    - releases
    - .final_builds
    uri: https://github.com/cloudfoundry/cf-release.git
- name: cf-release-tarball
  type: bosh-io-release
  source:
    repository: cloudfoundry/cf-release
- name: rootfs-release-tarball
  type: bosh-io-release
  source:
    repository: cloudfoundry/cflinuxfs2-rootfs-release
- name: consul-release-tarball
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/consul-release
- name: etcd-release-tarball
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/etcd-release
- name: diego-release
  type: git
  source:
    branch: master
    ignore_paths:
    - dev_releases
    - git_hooks
    - releases
    - .final_builds
    uri: https://github.com/cloudfoundry-incubator/diego-release.git
- name: diego-release-tarball
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/diego-release
- name: garden-linux-release-tarball
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/garden-linux-release
- name: kubernetes-release
  type: git
  source:
    branch: master
    ignore_paths:
    - dev_releases
    - git_hooks
    - releases
    - .final_builds
    uri: https://github.com/sykesm/kubernetes-release.git
- name: boshlite-cf
  type: bosh-deployment
  source:
    target: {{bosh-lite-target}}
    username: {{bosh-lite-user}}
    password: {{bosh-lite-password}}
    deployment: cf-warden
- name: boshlite-diego
  type: bosh-deployment
  source:
    target: {{bosh-lite-target}}
    username: {{bosh-lite-user}}
    password: {{bosh-lite-password}}
    deployment: cf-warden-diego
- name: boshlite-kubernetes
  type: bosh-deployment
  source:
    target: {{bosh-lite-target}}
    username: {{bosh-lite-user}}
    password: {{bosh-lite-password}}
    deployment: kubernetes

jobs:
- name: boshlite-deploy
  public: true
  serial_groups: [boshlite]
  plan:
  - aggregate:
    - get: boshlite-stemcell
      trigger: true
    - get: cf-release
      trigger: true
      params:
        depth: 10
        submodules: none
    - get: cf-release-tarball
      trigger: true
    - get: consul-release-tarball
      trigger: true
    - get: diego-release
      trigger: true
      params:
        depth: 10
        submodules: none
    - get: diego-release-tarball
      trigger: true
    - get: etcd-release-tarball
      trigger: true
    - get: garden-linux-release-tarball
      trigger: true
    - get: kubernetes-release
      params:
        depth: 10
        submodules: none
      trigger: true
    - get: rootfs-release-tarball
      trigger: true
  - task: create-kubernetes-release
    config:
      image_resource:
        type: docker-image
        source: { repository: sykesm/bosh-deploy }
      platform: linux
      inputs:
      - name: kubernetes-release
      outputs:
      - name: kubernetes-release-tarball
      run:
        path: bash
        args:
        - -c
        - |
          set -e
          bosh -n create release --version $(date "+%s") --with-tarball --name kubernetes --dir kubernetes-release
          cp kubernetes-release/dev_releases/kubernetes/*.tgz kubernetes-release-tarball/
  - task: generate-manifests
    config:
      image_resource:
        type: docker-image
        source: { repository: sykesm/bosh-deploy }
      platform: linux
      inputs:
      - name: cf-release
      - name: diego-release
      - name: kubernetes-release
      outputs:
      - name: manifests
      run:
        path: bash
        args:
        - -c
        - |
          set -e
          bosh -n target {{bosh-lite-target}} lite
          bosh login {{bosh-lite-user}} {{bosh-lite-password}}

          export CF_MANIFESTS_DIR=$PWD/cf-release/bosh-lite/deployments/cf.yml
          ( cd cf-release && ./scripts/generate-bosh-lite-dev-manifest )
          ( cd diego-release && ./scripts/generate-bosh-lite-manifests )

          cp cf-release/bosh-lite/deployments/cf.yml manifests
          cp diego-release/bosh-lite/deployments/diego.yml manifests
          cat kubernetes-release/manifests/kubernetes-manifest.yml | grep -v director_uuid > manifests/kubernetes.yml
  - put: boshlite-cf
    params:
      cleanup: true
      manifest: manifests/cf.yml
      stemcells:
      - boshlite-stemcell/*.tgz
      releases:
      - cf-release-tarball/*.tgz
  - put: boshlite-diego
    params:
      cleanup: true
      manifest: manifests/diego.yml
      stemcells:
      - boshlite-stemcell/*.tgz
      releases:
      - diego-release-tarball/*.tgz
      - etcd-release-tarball/*.tgz
      - garden-linux-release-tarball/*.tgz
      - rootfs-release-tarball/*.tgz
  - put: boshlite-kubernetes
    params:
      cleanup: true
      manifest: manifests/kubernetes.yml
      stemcells:
      - boshlite-stemcell/*.tgz
      releases:
      - consul-release-tarball/*.tgz
      - etcd-release-tarball/*.tgz
      - kubernetes-release-tarball/*.tgz
